apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openstack-actions-runner.fullname" . }}
  labels:
    {{- include "openstack-actions-runner.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openstack-actions-runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openstack-actions-runner.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openstack-actions-runner.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: "GITHUB_TOKEN"
              valueFrom:
                secretKeyRef:
                  key: githubToken
                  name: {{ .Release.Name }}-auth
            - name: "CLOUD_NINE_TENANT"
              valueFrom:
                secretKeyRef:
                  key: cloudNineTenant
                  name: {{ .Release.Name }}-auth
            - name: "CLOUD_NINE_TOKEN"
              valueFrom:
                secretKeyRef:
                  key: cloudNineToken
                  name: {{ .Release.Name }}-auth

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
