apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openstack-actions-runner.fullname" . }}-web
  labels:
    role: web
    {{- include "openstack-actions-runner.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openstack-actions-runner.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      annotations:
        checksum/settings: {{ include (print $.Template.BasePath "/settings.yml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        role: web
        {{- include "openstack-actions-runner.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openstack-actions-runner.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.web.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["uvicorn"]
        args: ["web.main:app", "--host", "0.0.0.0", "--port", "80"]
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redis.fullnameOverride }}
              key: redis-password
        - name: REDIS_HOST
          value: {{ .Values.redis.fullnameOverride  }}-master
        - name: REDIS_PORT
          value: "{{ .Values.redis.redisPort }}"
        envFrom:
        - configMapRef:
            name: "{{ .Release.Name }}-config"
        - secretRef:
            name: {{ .Release.Name }}-auth
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-settings

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
