apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  githubToken:   {{ .Values.githubToken | b64enc }}
  githubOrganization:   {{ .Values.githubOrganization | b64enc }}
  cloudNineTenant: {{ .Values.cloudNineTenant | b64enc }}
  cloudNineToken:  {{ .Values.cloudNineToken | b64enc }}
  cloudNineUsername:  {{ .Values.cloudNineUsername | b64enc }}
  cloudNinePassword:  {{ .Values.cloudNinePassword | b64enc }}
