apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  GITHUB_TOKEN:   {{ .Values.GITHUB_TOKEN | b64enc }}
  CLOUD_9_TENANT: {{ .Values.CLOUD_9_TENANT | b64enc }}
  CLOUD_9_TOKEN:  {{ .Values.CLOUD_9_TOKEN | b64enc }}
