apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  githubToken:   {{ .Values.githubToken | b64enc }}
  cloudNineTenant: {{ .Values.cloudNineTenant | b64enc }}
  cloudNineToken:  {{ .Values.cloudNineToken | b64enc }}
