apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  GITHUB_TOKEN:   {{ .Values.githubToken | b64enc }}
  CLOUD_NINE_TOKEN:  {{ .Values.cloudNineToken | b64enc }}
  CLOUD_NINE_USERNAME:  {{ .Values.cloudNineUsername | b64enc }}
  CLOUD_NINE_PASSWORD:  {{ .Values.cloudNinePassword | b64enc }}
