apiVersion: v1
kind: Service
metadata:
  name: {{ include "openstack-actions-runner.fullname" . }}-manager
  labels:
    role: manager
    {{- include "openstack-actions-runner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.deployment.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.metricsPort }}
      protocol: TCP
  selector:
    role: manager
    {{- include "openstack-actions-runner.selectorLabels" . | nindent 4 }}
