version: "3.9"
services:
  web:
    build: .
    command:
      - python3
      - /app/runners_manager/start.py
      - --settings-file=/app/settings.yaml
    volumes:
    - ./runners_manager:/app/runners_manager
    - ./settings.yaml:/app/settings.yaml
    depends_on:
      - redis
    env_file:
      - .env
    environment:
       - PYTHONUNBUFFERED=0
       - PYTHONIOENCODING=UTF-8
  redis:
    image: "redis:alpine"
