version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python3 /app/srcs/web/app.py
    volumes:
      - "./srcs:/app/srcs"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=0
      - PYTHONIOENCODING=UTF-8
    ports:
      - "8080:8080"
  redis:
    image: "redis:alpine"
